#可修改
[base]
video_input = ['36-side.mp4']  #相对路径绝对路径都可以
first_person_height = 1.75  #测试人身高
time_range = []  #可自行选择分析视频开始和结束的秒数
show_realtime_results = false  #是否实时显示分析结果
save_vid = true #是否保存分析后的带标记点的视频
save_img = false  #是否保存逐帧图片；true的话运行时间会加长
result_dir = '36'   #视频分析结果保存路径；如果为空，则在当前目录下



#不可修改
nb_persons_to_detect = '1'
person_ordering_method = 'greatest_displacement'
load_trc_px = ''
compare = false
visible_side = ['left']
video_dir = ''
save_pose = true
calculate_angles = false
save_angles = false
input_size = [1280, 720]
[pose]
slowmo_factor = 1
pose_model = 'Body_with_feet'
mode = 'balanced'
det_frequency = 16
device = 'CUDA'   # CUDA
backend = 'onnxruntime'
tracking_mode = 'sports2d'
keypoint_likelihood_threshold = 0.5  
average_likelihood_threshold = 0.7
keypoint_number_threshold = 0.5
max_distance = 250
max_unseen_time = 1.0
[px_to_meters_conversion]
to_meters = true
make_c3d = false
save_calib = false
floor_angle = 'auto'
xy_origin = ['auto']
perspective_value = 4
perspective_unit = 'distance_m'
distortions = [0.0, 0.0, 0.0, 0.0, 0.0]
calib_file = ''
[angles]
joint_angles = ['Right ankle', 'Left ankle', 'Right knee', 'Left knee', 'Right hip', 'Left hip']# ['Right ankle', 'Left ankle', 'Right knee', 'Left knee', 'Right hip', 'Left hip', 'Right shoulder', 'Left shoulder', 'Right elbow', 'Left elbow', 'Right wrist', 'Left wrist']
segment_angles = []# ['Right foot', 'Left foot', 'Right shank', 'Left shank', 'Right thigh', 'Left thigh', 'Pelvis', 'Trunk', 'Shoulders', 'Head', 'Right arm', 'Left arm', 'Right forearm', 'Left forearm']
display_angle_values_on = ['body']
fontSize = 1
correct_segment_angles_with_floor_angle = true
[post-processing]
save_graphs =false  #是否保存关节角度图片
interpolate = true
interp_gap_smaller_than = 100
fill_large_gaps_with = 'last_value'
#sections_to_keep = 'all'
min_chunk_size = 60
reject_outliers = true
filter = true
show_graphs = false
filter_type = 'butterworth'
   [post-processing.butterworth]
   cut_off_frequency = 6
   order = 4
   [post-processing.kalman]
   trust_ratio = 500
   smooth = true
   [post-processing.gcv_spline]
   gcv_cut_off_frequency = 'auto'
   gcv_smoothing_factor = 0.1
   [post-processing.loess]
   nb_values_used = 5
   [post-processing.gaussian]
   sigma_kernel = 1
   [post-processing.median]
   kernel_size = 3
   [post-processing.butterworth_on_speed]
   order = 4
   cut_off_frequency = 10
[kinematics]
do_ik = false
use_augmentation = false
feet_on_floor = false
use_simple_model = false
participant_mass = [55.0, 67.0]
right_left_symmetry = true
default_height = 1.7
large_hip_knee_angles = 135
trimmed_extrema_percent = 0.5
remove_individual_scaling_setup = true
remove_individual_ik_setup = true
[logging]
use_custom_logging = false
[[pose.CUSTOM]]
name = "Hip"
id = 19
  [[pose.CUSTOM.children]]
  name = "RHip"
  id = 12
     [[pose.CUSTOM.children.children]]
     name = "RKnee"
     id = 14
        [[pose.CUSTOM.children.children.children]]
        name = "RAnkle"
        id = 16
           [[pose.CUSTOM.children.children.children.children]]
           name = "RBigToe"
           id = 21
              [[pose.CUSTOM.children.children.children.children.children]]
              name = "RSmallToe"
              id = 23
           [[pose.CUSTOM.children.children.children.children]]
           name = "RHeel"
           id = 25
  [[pose.CUSTOM.children]]
  name = "LHip"
  id = 11
     [[pose.CUSTOM.children.children]]
     name = "LKnee"
     id = 13
        [[pose.CUSTOM.children.children.children]]
        name = "LAnkle"
        id = 15
           [[pose.CUSTOM.children.children.children.children]]
           name = "LBigToe"
           id = 20
              [[pose.CUSTOM.children.children.children.children.children]]
              name = "LSmallToe"
              id = 22
           [[pose.CUSTOM.children.children.children.children]]
           name = "LHeel"
           id = 24